### ISSUE TITLE
certificate format consistency required

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#838] opened 2021-12-01 02:09 UTC
I have noticed that pem cert format requirements are not consistent across multiple resources

e.g.  idp_saml_key requires base64 encoded

https://registry.terraform.io/providers/okta/okta/latest/docs/resources/idp_saml_key

but domain_certificate requires non base64 format but in single line

https://registry.terraform.io/providers/okta/okta/latest/docs/resources/domain_certificate

**Comment by bogdanprodanj** [comment] 2021-12-01 07:49
Hi, @ahmei0! Thanks for submitting this issue! That inconsistency is caused by the Okta API itself and not the terraform provider. 
* Cert [example](https://developer.okta.com/docs/reference/api/domains/#certificate-object) for domain certificate.
* Cert [example ](https://developer.okta.com/docs/reference/api/idps/#request-example-25) for IdP SAML key.

**Comment by monde** [comment] 2022-02-02 21:34
Closing on upstream behavior.

**Closed as completed by monde** 2022-02-02 21:34 UTC
Labels: wontfix, upstream
