### ISSUE TITLE
okta_app_user_schema_property fails when applying multiple new properties

### ISSUE THREAD

**Issue by stmyers** [okta/terraform-provider-okta#632] opened 2021-09-08 10:36 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.14.7
+ provider registry.terraform.io/okta/okta v3.13.7

### Affected Resource(s)

- okta_app_user_schema_property

### Terraform Configuration Files

This is a snippet essentially...there are 29 properties that are being added
```hcl
resource "okta_app_saml" "test_app" {
  label                    = "app test"
  sso_url                  = "https://samltest.id/saml/sp"
  recipient                = "https://samltest.id/saml/sp"
  destination              = "https://samltest.id/saml/sp"
  audience                 = "https://samltest.id/Shibboleth.sso/SAML2/POST"
  subject_name_id_template = "$${user.userName}"
  subject_name_id_format   = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
  response_signed          = true
  assertion_signed         = true
  signature_algorithm      = "RSA_SHA256"
  digest_algorithm         = "SHA256"
  honor_force_authn        = true
  authn_context_class_ref  = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
  #logo                     = "./test_app.png"
  hide_web = false
}

resource "okta_app_user_schema_property" "test_app_costCenterName" {
  app_id        = okta_app_saml.test_app.id
  index         = "costCenterName"
  external_name = "costCenterName"
  title         = "Cost Center Name"
  type          = "string"
  permissions   = "READ_WRITE"
}

resource "okta_app_user_schema_property" "test_app_countryName" {
  app_id        = okta_app_saml.test_app.id
  index         = "countryName"
  external_name = "countryName"
  title         = "Country Name"
  type          = "string"
  permissions   = "READ_WRITE"
}
```

### Debug Output

Partial trace output 
https://gist.github.com/stmyers/846a83ced829a5695ea4970a0a6745ce 

### Expected Behavior

App and all properties are created

### Actual Behavior

App is created, and several properties are created, but several fail with generic error.  Subsequent `apply` operations results in a few more properties created, but it takes multiple runs to complete all properties.
```
Error: application user schema property costCenterName was not created in app 0oa1u8vn6yaShOatM0x7

  on app_username-test.tf line 50, in resource "okta_app_user_schema_property" "test_app_costCenterName":
  50: resource "okta_app_user_schema_property" "test_app_costCenterName" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by bogdanprodan-okta** [comment] 2021-09-08 20:58
Hi @stmyers! Thanks for submitting this issue! It's a duplicate of #604 and will be resolved shortly.

**Closed as completed** 2021-09-08 21:39 UTC
