### ISSUE TITLE
okta_group_roles resource is missing features to specify "all {apps|groups}" or "specific {apps|groups}"

### ISSUE THREAD

**Issue by ThomasWatling** [okta/terraform-provider-okta#189] opened 2020-09-29 15:11 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The okta_group_roles resource (https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/group_roles) allows you to assign a group to admin permissions. Some of these admin permissions, e.g. Help Desk Administrator `HELP_DESK_ADMIN`, allow you to subsequently choose in the Okta GUI whether this means "Can administer all users" or "Can administer users in specific groups", and if you choose the latter you then specify the groups. This is similar for "Group Membership Admin Permissions", "Application Administrator", "Group Administrator". 

With the terraform resource, you cannot indicate if you want to constrain the groups/apps the admin can manage (i.e. it defaults to "Can administer all users" and the alternative option is not possible). 

This behaviour does appear possible with the Okta API directly https://developer.okta.com/docs/reference/api/roles/#add-group-target-to-group-administrator-role-given-to-a-group, it also explains the behaviour is incremental - i.e. "all apps/groups" by default, but then specify a app/group to scope the behaviour.

**Comment by RichiCoder1** [comment] 2020-12-03 19:44
_bump_. This is important for managing groups via terraform

**Comment by bogdanprodan-okta** [comment] 2021-01-31 18:22
Duplicate of https://github.com/oktadeveloper/terraform-provider-okta/issues/280

**Closed as completed by bogdanprodan-okta** 2021-01-31 18:22 UTC
Labels: enhancement
