### ISSUE TITLE
okta_app_oauth caches client_secret forever

### ISSUE THREAD

**Issue by nathankodilla** [okta/terraform-provider-okta#109] opened 2020-04-09 12:53 UTC
Terraform v0.12.24
Okta v3.1.1

If you switch the token_endpoint_auth_method, Okta will generate a new client_secret. However, the output in terraform is always the first one that was created.

**Comment by nathankodilla** [comment] 2020-06-09 00:51
Anyone able to address this?

**Comment by bogdanprodan-okta** [comment] 2021-01-24 14:31
Hi @nathankodilla! According to the [official documentation](https://developer.okta.com/docs/reference/api/apps/#oauth-credential-object), `client_secret` is only available on app creation, so when terraform provider calls "get app" endpoint, it is always empty. 
However, seems like `client_secret` is changed when changing `token_endpoint_auth_method`:
Original:
```
resource "okta_app_oauth" "test" {
  label                      = "testAcc_replace_with_uuid"
  type                       = "web"
  grant_types                = ["authorization_code"]
  redirect_uris              = ["http://d.com/"]
  response_types             = ["code"]
  client_id                  = "something_from_somewhere"
  token_endpoint_auth_method = "client_secret_basic"
  consent_method             = "TRUSTED"
}
```
Updated:
```
resource "okta_app_oauth" "test" {
  label                      = "testAcc_replace_with_uuid"
  type                       = "web"
  grant_types                = ["authorization_code"]
  redirect_uris              = ["http://d.com/"]
  response_types             = ["code"]
  client_id                  = "something_from_somewhere"
  consent_method             = "TRUSTED"
  token_endpoint_auth_method = "private_key_jwt"
  jwks {
    kty = "RSA"
    kid = "SIGNING_KEY"
    e   = "AQAB"
    n   = "owfoXNHcAlAVpIO41840ZU2tZraLGw3yEr3xZvAti7oEZPUKCytk88IDgH7440JOuz8GC_D6vtduWOqnEt0j0_faJnhKHgfj7DTWBOCxzSdjrM-Uyj6-e_XLFvZXzYsQvt52AnBJUV15G1W9QTjlghT_pFrW0xrTtbO1c281u1HJdPd5BeIyPb0pGbciySlx53OqGyxrAxPAt5P5h-n36HJkVsSQtNvgptLyOwWYkX50lgnh2szbJ0_O581bqkNBy9uqlnVeK1RZDQUl4mk8roWYhsx_JOgjpC3YyeXA6hHsT5xWZos_gNx98AHivNaAjzIzvyVItX2-hP0Aoscfff"
  }
}
```
In the first case, `client_secret` was some random string, and in the second it became empty. 
I'm closing this issue since I wasn't able to reproduce the bug, but feel free to leave a comment if this needs to be reopened.

**Closed as completed by bogdanprodan-okta** 2021-01-24 14:31 UTC
Labels: bug, needs-investigation
