### ISSUE TITLE
Factor Sequence - MFA type per group

### ISSUE THREAD

**Issue by drewmullen** [okta/terraform-provider-okta#510] opened 2021-06-22 16:55 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would love to be able to set MFA types for different groups via "Factor Sequence" (pic below). I dont see this in the existing provider. I would be interested in writing this feature if I can get some guidance on:

- would this be a new resource or attribute to an existing?
- Is this already implemented in the go sdk? can you provide a link of it or where it might go?

![image](https://user-images.githubusercontent.com/3812162/122967737-c889f800-d358-11eb-8c65-912fe3bca4d1.png)

### New or Affected Resource(s)

this is a guess:
- resource_okta_policy_sign_on

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by drewmullen** [comment] 2021-07-02 18:36
i think the authtype update would be [here](https://github.com/okta/terraform-provider-okta/blob/24870791bb606f2e17b0be31a45f00b6e37d2e24/okta/resource_okta_policy_rule_sign_on.go#L25) and then factor sequence might be an entirely new resource

**Comment by bogdanprodan-okta** [comment] 2021-07-02 19:04
I think this is duplicate of #420

**Comment by bogdanprodan-okta** [comment] 2021-07-02 19:05
> i think the authtype update would be [here](https://github.com/okta/terraform-provider-okta/blob/24870791bb606f2e17b0be31a45f00b6e37d2e24/okta/resource_okta_policy_rule_sign_on.go#L25) and then factor sequence might be an entirely new resource

I'm working on it!

**Closed as completed** 2021-07-02 19:13 UTC
Labels: enhancement
