### ISSUE TITLE
Doesnt appear to be a way to add scope to an application

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#237] opened 2020-12-15 09:47 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "middleware" {
  label          = "middleware"
  type           = "service"
  response_types = ["token"]
  grant_types    = ["client_credentials"]
  token_endpoint_auth_method = "private_key_jwt"

  jwks {
    kty = "RSA"
    kid = "c08ff170-a666-404d-hhhhhhhh
    e   = "AQAB"
    n   = "bbbbbbbbbbbb"
  }
}
```

### Expected Behavior

I would like to add the okta.manage.groups, okta.manage.user scopes

### Actual Behavior
I cant add scopes to the application

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment] 2020-12-15 18:59
Hi @mcrobbj! Thanks for creating this issue! I'll check it shortly and will get back to you asap.

**Comment by tgoodsell-tempus** [comment] 2020-12-15 22:53
Probably requires a new resource associated with the OAUTH apps?

Reference: https://developer.okta.com/docs/reference/api/apps/#application-oauth-2-0-scope-consent-grant-operations

**Comment by mcrobbj** [comment] 2020-12-16 09:38
> Probably requires a new resource associated with the OAUTH apps?
> 
> Reference: https://developer.okta.com/docs/reference/api/apps/#application-oauth-2-0-scope-consent-grant-operations

I think so, you also probably need the do the get for existing okta scopes such as okta.users.manage as the api's work off id's rather than names.

**Comment by CodyDunlap** [comment] 2021-02-23 17:53
Is this a duplicate of #69?

**Comment by mcrobbj** [comment] 2021-03-01 09:34
Sorry yes it does seem to be a duplicate

**Comment by mcrobbj** [comment] 2021-03-01 10:08
#356 <https://github.com/oktadeveloper/terraform-provider-okta/pull/356> states
that its fix and it looks like it would be but its not been released.

**Comment by patrickmarshallcb** [comment] 2021-03-01 12:24
Looking to add scope to the application also, just wondering how long does it usually take for a new feature to be pushed to release. Thanks for this.

**Comment by bogdanprodan-okta** [comment] 2021-03-01 12:30
> Looking to add scope to the application also, just wondering how long does it usually take for a new feature to be pushed to release. Thanks for this.

Hi! You can check the releases for the past several months to get an idea about the frequency of new features' appearance. Usually, it takes 2-3 weeks for the feature to be released, sometimes even less than that. It all depends on the complexity, how well it is documented in the official Okta specs, etc. Currently, I'm trying to make new releases every week.

**Comment by patrickmarshallcb** [comment] 2021-03-01 13:45
> > Looking to add scope to the application also, just wondering how long does it usually take for a new feature to be pushed to release. Thanks for this.
> 
> Hi! You can check the releases for the past several months to get an idea about the frequency of new features' appearance. Usually, it takes 2-3 weeks for the feature to be released, sometimes even less than that. It all depends on the complexity, how well it is documented in the official Okta specs, etc. Currently, I'm trying to make new releases every week.

Thanks for the feedback, really appreciate it.

**Closed as completed** 2021-03-03 12:24 UTC
Labels: dependencies
