### ISSUE TITLE
Workflow resource details in terraform registery

### ISSUE THREAD

**Issue by Devi0909** [okta/terraform-provider-okta#1374] opened 2022-11-17 12:42 UTC
Hi ,

We are trying to import Okta workflows from source tenant to target tenant.

But we did not find the resource name in terraform registry.

"https://registry.terraform.io/providers/okta/okta/latest/docs"

Currently does workflows are in scope? If yes, please let us know the resource details.

**Comment by monde** [comment] 2022-11-17 17:43
Hi @Devi0909 The workflows API isn't documented in the public API docs https://developer.okta.com/docs/reference/core-okta-api/ . Specifically, the Okta Terraform Provider is oriented towards the management operations in the public API.

Again, please open support tickets for getting help and support for your Terraform usage https://support.okta.com/help/s/?language=en_US . And use Github issues for bug reports and new feature requests. You might ask yourself, is this not a feature request? Yes, but the request is for Okta's public API support. Feature requests here should be used when there is behavior and attributes listed in the management API docs but not yet implemented in the Terraform provider.

When you open a support ticket with Okta it registers internally how the community would like to improve the service, the public API, etc.

Thanks

**Comment by monde** [comment] 2023-03-09 19:50
cc @jefftaylor-okta

**Comment by monde** [comment] 2023-03-10 17:55
This a duplicate of #981, let's track our progress on this feature there.

**Closed as completed by monde** 2023-03-10 17:55 UTC
Labels: duplicate, no-api, support-discussion
