### ISSUE TITLE
`api_token` is always required agrument for provider, no matter are resources will be created or not

### ISSUE THREAD

**Issue by MaxymVlasov** [okta/terraform-provider-okta#1564] opened 2023-05-19 14:27 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.9
on linux_amd64

### Affected Resource(s)

`provider "okta" {}` itself when `okta_app_oauth` exist

### Terraform Configuration Files

```hcl
provider "okta" {
  alias     = "central"
  org_name  = null
  base_url  = null
  api_token = null
}

resource "okta_app_oauth" "okta_oauth_basic_app" {
  count = 0 # RESOURCE DISABLED

  label          = "module.this.id"
  type           = "service"
  grant_types    = ["client_credentials"]
  response_types = ["token"]
  profile = jsonencode({
    label = "module.this.id"
  })

  provider = okta.central
}
```

### Debug Output

https://gist.github.com/MaxymVlasov/1b3ca023a0c7ac047d8c39fb6631c987

```
╷
│ Error: [ERROR] invalid configuration: your Okta API token is missing. You can generate one in the Okta Developer Console. Follow these instructions: https://bit.ly/get-okta-api-token
│ 
│   with module.app.provider["registry.terraform.io/okta/okta"].central,
│   on ../app/okta-central.tf line 1, in provider "okta":
│    1: provider "okta" {
│ 
```

### Expected Behavior

Just make `api_token` not required field for init provider:

```
No changes. Your infrastructure matches the configuration.
```

Because next standalone code works well:

```terraform
provider "okta" {
  alias     = "central"
  org_name  = null
  base_url  = null
  api_token = null
}
```

#### Can this be done in the Admin UI?

N/A

#### Can this be done in the actual API call?

N/A

### Steps to Reproduce

1. Create file with code from [Terraform Configuration Files](#terraform-configuration-files) section
2. `terraform init`
3. `terraform plan`

### References

- #0000

## Use case

We have a tf-module for apps, that provides the possibility to opt-in usage of 3 different Okta providers and many other stuff. Right now, about 95% of apps not use at all or do use not all 3 Okta providers, but we still need to call Okta API to get tokens, to do nothing.

Based on how other providers work, I can say that requiring `api_token` and having no ability to set it to mock value or `null` - it's a bug, which increases your API load and provides tf-code management problems to us (lose-lose situation)

For example, here how the same issue was fixed for MongoDB Atlas provider

![image](https://github.com/okta/terraform-provider-okta/assets/11096782/daec2bc7-4471-48cd-b1a0-d68ba0b5df8c)

As you might have guessed, MongoDB will not work without `public_key` and `private_key` (which can be specified in [many different ways](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs#authenticate-the-provider)), but its not try to connect to API when no resources will be created.

**Comment by monde** [comment] 2023-05-23 15:36
This is a duplicate of #1551 and we are looking to address implementing lazy init.

**Comment by monde** [comment] 2023-05-23 15:36
Thanks for the write up @MaxymVlasov

**Closed as completed by monde** 2023-05-23 15:36 UTC
