### ISSUE TITLE
Documentation incorrect for "okta_user_group_memberships" and "okta_user_admin_roles"

### ISSUE THREAD

**Issue by plynch-magnolia** [okta/terraform-provider-okta#1613] opened 2023-06-27 14:13 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.1

### Affected Resource(s)

- okta_user_group_memberships
- okta_user_admin_roles
- okta_user

### Terraform Configuration

```hcl
resource "okta_user" "john_smith" {
  email      = "john.smith@domain.com"
  login      = "john.smith@domain.com"
  first_name = "John"
  last_name  = "Smith"

  lifecycle {
    ignore_changes = [admin_roles, group_memberships, profile_url]
  }
}
```

### Error Output

```
│ Error: Unsupported attribute
│
│   on users.tf line 10, in resource "okta_user" "john_smith":
│   10:     ignore_changes = [admin_roles,group_memberships,profile_url]
│
│ This object has no argument, nested block, or exported attribute named "admin_roles".
╵
╷
│ Error: Unsupported attribute
│
│   on users.tf line 10, in resource "okta_user" "john_smith":
│   10:     ignore_changes = [admin_roles,group_memberships,profile_url]
│
│ This object has no argument, nested block, or exported attribute named "group_memberships".
```

### Expected Behavior

No changes in plans

#### Can this be done in the Admin UI?

I don't know

#### Can this be done in the actual API call?

 I don't know

### Actual Behavior

Error is thrown

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The error is only within the documentation

### References
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/user_admin_roles
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/user_group_memberships

**Comment by duytiennguyen-okta** [comment] 2023-06-27 15:15
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-622580

**Comment by duytiennguyen-okta** [comment] 2023-10-12 16:18
@plynch-magnolia okta_user no longer has admin_roles and group_memberships, which we removed during the [v4 release](https://github.com/okta/terraform-provider-okta/issues/1338), so you need to remove those from the lifecycle. okta_user_admin_roles and okta_user_group_memberships should be working as intended though. I am closing this issue as it is no longer needed

**Closed as completed by duytiennguyen-okta** 2023-10-12 16:18 UTC
Labels: triaged, documentation-bug
