### ISSUE TITLE
Add support for magic link

### ISSUE THREAD

**Issue by bbratchiv** [okta/terraform-provider-okta#2152] opened 2024-12-04 15:00 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

<hr>

### Description
As per https://devforum.okta.com/t/email-magic-link-terraform-question/26802 the magic link is not supported in Terraform.
Please implement this resource

### New or Affected Resource(s)

- okta_app_oauth

It's looks like this 
<img width="710" alt="image" src="https://github.com/user-attachments/assets/55222977-faa7-4ca5-b38f-914335d97809">

**Comment by duytiennguyen-okta** [comment] 2024-12-10 16:55
Duplicate of #1740

**Closed as completed by duytiennguyen-okta** 2024-12-10 16:55 UTC
Labels: enhancement
