### ISSUE TITLE
okta_group_role fails with API and breaks terraform state 

### ISSUE THREAD

**Issue by mfergus1** [okta/terraform-provider-okta#448] opened 2021-04-27 23:25 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_group_role

### Terraform Configuration Files

```
resource "okta_group_role" "app_admins" {
  group_id  = okta_group.admins.id
  role_type = "APP_ADMIN"
  target_app_list = [
    "${var.app_name}.${var.app_id}"
  ]
}
```

### Actual Behavior
```
Error: unable to add app targets to role assignment <REDACTED> for group <REDACTED>: failed to add an app instance target to an app administrator role given to a group: The API returned an error: Bad request.
```
Yet, the role does get created and my terraform state is broken. 

```
Error: failed to assign role APP_ADMIN to group <REDACTED>: The API returned an error: The role specified is already assigned to the user.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment] 2021-04-28 07:46
Hi, @mfergus1! Thanks for submitting this issue! I'll try to reproduce your steps and get back to you ASAP.

**Comment by mfergus1** [comment] 2021-04-28 16:52
Thanks @bogdanprodan-okta :) 
1) App name and OIDC
I will caveat / note that I am aware by default all OIDC apps have the "name" OIDC_Client which I'm curious about overriding as that is a value passed to the group role assignment target list. :shrug:
So... `app_name` doesn't really apply for them (I was hoping that client_id might be something I override that becomes the OIDC app_name).

2) In the end, the role is created and the group is given *global* app admin

**Comment by mfergus1** [comment] 2021-05-03 21:38
@bogdanprodan-okta any progress here? we are working on fulfilling some security requirements and are limited in enabling our team for distributed management of enterprise apps

**Comment by CodyDunlap** [comment] 2021-05-04 18:02
I'm not sure if it's related but I'm getting some errors from `okta_group_role` that are causing state to become corrupted as well. 

I have a group of users that I'm assigning multiple admin roles to, using `okta_group_role`. Seems to be that the multiple `okta_group_role` resources are conflicting with each other. One run, I'll get an error like the one below indicating it couldn't assign role A and that the output was inconsistent. But it will assign role B-D to the user in Okta, but doesn't record it in terraform state. Then the next run, One of the other roles will be attempted and it fails because it already exists.

Here's my error: 

```
Terraform v0.14.4
Configuring remote state backend...
Initializing plugins and modules...
okta_group_role.software_api_manager: Creating...
okta_group_role.software_admin_read_only: Creating...
okta_group_role.software_api_manager: Creation complete after 1s [id=graookvk0pT7vDLcT1d6]
okta_group_role.software_admin_read_only: Creation complete after 1s [id=graoohb2fb2GiMavU1d6]
okta_group_role.software_org_admin: Creating...

Error: Provider produced inconsistent result after apply

When applying changes to okta_group_role.software_org_admin, provider
"registry.terraform.io/oktadeveloper/okta" produced an unexpected new value:
Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

**Comment by bogdanprodan-okta** [comment] 2021-05-10 12:43
> I'm not sure if it's related but I'm getting some errors from `okta_group_role` that are causing state to become corrupted as well.
> 
> I have a group of users that I'm assigning multiple admin roles to, using `okta_group_role`. Seems to be that the multiple `okta_group_role` resources are conflicting with each other. One run, I'll get an error like the one below indicating it couldn't assign role A and that the output was inconsistent. But it will assign role B-D to the user in Okta, but doesn't record it in terraform state. Then the next run, One of the other roles will be attempted and it fails because it already exists.
> 
> Here's my error:
> 
> ```
> Terraform v0.14.4
> Configuring remote state backend...
> Initializing plugins and modules...
> okta_group_role.software_api_manager: Creating...
> okta_group_role.software_admin_read_only: Creating...
> okta_group_role.software_api_manager: Creation complete after 1s [id=graookvk0pT7vDLcT1d6]
> okta_group_role.software_admin_read_only: Creation complete after 1s [id=graoohb2fb2GiMavU1d6]
> okta_group_role.software_org_admin: Creating...
> 
> Error: Provider produced inconsistent result after apply
> 
> When applying changes to okta_group_role.software_org_admin, provider
> "registry.terraform.io/oktadeveloper/okta" produced an unexpected new value:
> Root resource was present, but now absent.
> 
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.
> ```

Hi, @CodyDunlap! It's probably because of how the provider works. It makes creates the resource and then reads it and sometimes Okta lags and creates resources with some delay. This causes a `404` error and terraform will throw `Root resource was present, but now absent.` I'll add a retry for this resource, so it will wait for the resource to be created.

**Comment by bogdanprodan-okta** [comment] 2021-05-10 13:05
> @bogdanprodan-okta any progress here? we are working on fulfilling some security requirements and are limited in enabling our team for distributed management of enterprise apps

Hi, @mfergus1! The reason you are receiving `400 Bad Request` is that your `var.app_name` parameter is probably invalid. 
Here is the example that I tested on:
```hcl
resource "okta_app_saml" "jenkins" {
  label               = "jenkins 2222"
  preconfigured_app   = "jenkins"
  auto_submit_toolbar = true
  app_settings_json   = <<JSON
  {
    "baseUrl": "https://service.sumologic.com"
  }
JSON
  attribute_statements {
    type      = "EXPRESSION"
    name      = "Test"
    namespace = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
    values    = [
      "test"
    ]
  }
  attribute_statements {
    type         = "GROUP"
    name         = "Attr Two"
    filter_type  = "STARTS_WITH"
    filter_value = "test"
  }
}

resource "okta_group" "test" {
  name        = "testAcc_replace_with_uuid"
  description = "testing"
}

resource "okta_group_role" "app_admins" {
  group_id        = okta_group.test.id
  role_type       = "APP_ADMIN"
  /*target_app_list = [
    format("%s.%s", "SOME_INCORRECT_APP_NAME", okta_app_saml.jenkins.id)] */ // <-- incorrect naming that causes 400 Error
  target_app_list = [
    format("%s.%s", okta_app_saml.jenkins.name, okta_app_saml.jenkins.id)] // <-- correct name
}
```

**Comment by bogdanprodan-okta** [comment] 2021-07-24 18:12
Hi @mfergus1! Does this issue still occur or should I close it?

**Closed as completed** 2021-08-28 20:29 UTC
Labels: bug
