### ISSUE TITLE
Error: failed to get custom email sender: the API returned an error: This endpoint has been deprecated.

### ISSUE THREAD

**Issue by jvalderrama** [okta/terraform-provider-okta#1556] opened 2023-05-15 09:08 UTC
Provider Version: **3.46.0** and **4.0.0**
Resource: **okta_email_sender** 

```
resource "okta_email_sender" "example" {
  from_name    = "Paul Atreides"
  from_address = "no-reply@caladan.planet"
  subdomain    = "mail"
}
```

When it is applied it returns:
```

│ Error: failed to get custom email sender: the API returned an error: This endpoint has been deprecated., Status: 410 Gone
│ 
│   with okta_email_sender.current,
│   on email.tf line 1, in resource "okta_email_sender" "current":
│    1: resource "okta_email_sender" "current" {
│ 
```
Expected:
OK

**Comment by naveentrevonix** [comment] 2023-05-15 14:55
We are also receiving the same error, please let us if we have resolution.

**Comment by thekbb** [comment] 2023-05-15 20:18
This is a duplicate of #1537

**Comment by monde** [comment] 2023-05-16 15:05
Closing in favor of original #1537

**Closed as completed by monde** 2023-05-16 15:05 UTC
