### ISSUE TITLE
What happened to v3.6.1?

### ISSUE THREAD

**Issue by isometry** [okta/terraform-provider-okta#230] opened 2020-12-09 17:30 UTC
Apologies for the non-standard format, but there's not much to say…

Provider version v3.6.1 was originally released 22 days ago, but seems to have gone AWOL 4 hours ago. What happened? `terraform init` on new modules requiring the features in v3.6.1 is currently failing.

**Comment by joe-a-t** [comment] 2020-12-09 17:35
Duplicate of https://github.com/oktadeveloper/terraform-provider-okta/issues/229

**Closed as completed** 2020-12-09 18:18 UTC
Labels: duplicate
