### ISSUE TITLE
`okta_policy_device_assurance_*` - inability to add only Chrome Device Trust as policy

### ISSUE THREAD

**Issue by toddthiel** [okta/terraform-provider-okta#2048] opened 2024-07-23 21:47 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
`+ provider registry.terraform.io/okta/okta v4.8.1`

### Affected Resource(s)

* okta_policy_device_assurance_*

### Terraform Configuration Files

```hcl
resource "okta_policy_device_assurance_macos" "seb-macos" {
  name                         = "SEB MacOS Policy"
  third_party_signal_providers = true
  os_version                   = "11.0.0"
  #  tpsp_chrome_remote_desktop_app_blocked = true
  #  tpsp_builtin_dns_client_enabled        = true
  tpsp_device_enrollment_domain = var.google_domain
  tpsp_os_version               = "11.0.0"
  tpsp_disk_encrypted           = true
  tpsp_key_trust_level          = "CHROME_BROWSER_HW_KEY"
  #  tpsp_os_firewall                       = true
  #  tpsp_realtime_url_check_mode           = true
  #  tpsp_safe_browsing_protection_level    = "ENHANCED_PROTECTION"
  #  tpsp_screen_lock_secured               = true
  #  tpsp_site_isolation_enabled            = true
}
```

### Panic Output

I should be able to exclude all Okta Verify attributes, and keep this strictly related to `tpsp` fields. Instead, I'm getting Okta Verify attributes as a requirement. Any of the above fields that are commented out can be added just fine to the profile, it's when I exclude anything that's non `tpsp_` related from the policy, that the below error is thrown. 

#### Can this be done in the Admin UI?

Yes, I can create a Chrome Device Trust profile without including any fields related to Okta Verify. 

### Actual Behavior

```
│ Error: Invalid Attribute Combination
│ 
│   with okta_policy_device_assurance_macos.seb-macos,
│   on device-assurance.tf line 1, in resource "okta_policy_device_assurance_macos" "seb-macos":
│    1: resource "okta_policy_device_assurance_macos" "seb-macos" {
│ 
│ At least one attribute out of [disk_encryption_type,secure_hardware_present,screenlock_type] must be specified
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Consider this scenario: I don’t manage the devices used by Okta users—these could belong to contractors or be personal devices. However, I do control their Chrome Browser Profiles and can check the device’s security status using Chrome Device Trust. In such cases, I should be able to implement a Chrome Device Trust Device Assurance Policy on its own, without using Okta Verify. I can set this up in the dashboard, but not through Terraform. This feels like a bug. 

### References

- #0000

**Comment by duytiennguyen-okta** [comment] 2024-07-24 15:04
@toddthiel this is only related to macos and windows, and it is duplicate of #1764. Anw it should be fixed and released soon

**Closed as completed by duytiennguyen-okta** 2024-07-24 15:04 UTC
